config/routes.rb
Bllg::Application.routes.draw do
  

  resources :orders

  resources :posts do 
    resources :comments, :only => [:create]
end
  root :to => "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :comment, :location
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :billing_name, :shipping_name
  attr_writer :current_step

  validates_presence_of :shipping_name, :if => lambda {|o| o.current_step == "shipping"}
  validates_presence_of :billing_name, :if => lambda {|o| o.current_step == "billing"}

  def current_step
  	@current_step || steps.first
  	
  end
  def steps
  	%w[shipping billing confirmation]
  	
  end

  def next_step
  	self.current_step = steps[steps.index(current_step)+1]
  	
  end

  def previous_step
 self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
  	current_step == steps.first
  end

  def last_step?
  	current_step == steps.last
  end
  
  def all_valid?
  	steps.all? do |step|
  		self.current_step = step
  		valid?
  	end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :location, :message, :title
  validates_presence_of :title, :message, :location
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create!(params[:comment])
		redirect_to @post
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    session[:order_params] ||= {}
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    session[:order_params].deep_merge!(params[:order]) if params[:order]
    @order = Order.new(session[:order_params])
    @order.current_step = session[:order_step]
    if @order.valid?
      if params[:back_button]
        @order.previous_step
      elsif @order.last_step?
          @order.save if @order.all_valid?
      else
        @order.next_step
      end
      session[:order_step] = @order.current_step
    end
    if @order.new_record?
    render "new"
  else
    session[:order_step] = session[:order_params] = nil
    flash[:notice] = "Order saved"
    redirect_to @order
  end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  before_filter :authenticate, :except => [:index, :show]
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
       authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password =="password"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
<p>
	<strong>
		Posted <%= time_ago_in_words(comment.created_at) %> ago
	</strong>
	<%= comment.comment %>
	<%= comment.location %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bllg</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_billing_step.html.erb
  <h2>Billing Information</h2>
  <div class="field">
    <%= f.label :billing_name %><br />
    <%= f.text_field :billing_name %>
  </div>

app/views/orders/_confirmation_step.html.erb
 <h2>Confirmation Information</h2>
  <p>
    <strong>Shipping Information</strong>
    <%=h @order.shipping_name %>
  </p>
  <p>
    <strong>Billing Name</strong>
    <%=h @order.billing_name %>
  </p>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_shipping_step.html.erb
  <h2>Shipping Information</h2>
  <div class="field">
    <%= f.label :shipping_name %><br />
    <%= f.text_field :shipping_name %>
  </div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Shipping name</th>
    <th>Billing name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.shipping_name %></td>
    <td><%= order.billing_name %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
 <%= render "#{@order.current_step}_step", :f => f %>
  <div class="actions">
    <p><%= f.submit "Continue" %></p>
    <p><%= f.submit "Back", :name => "back_button" unless @order.first_step? %>
  </div>
<% end %>

 

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shipping name:</b>
  <%= @order.shipping_name %>
</p>

<p>
  <b>Billing name:</b>
  <%= @order.billing_name %>
</p>




<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <h2><%= link_to_unless_current post.title, post %></h2>
 <%= simple_format post.message %>
 <%= simple_format post.location %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<%= render :partial => @posts %>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => @post %><br>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<h2>Comments</h2>
<div id="comments">
	<%= render :partial => @post.comments %>
</div>

<%= form_for [@post, Comment.new] do |f| %>
	<p>
		<%= f.label :comment, "New Comment" %><br>
		<%= f.text_area :comment %><br>
		<%= f.label :location, "Location" %><br>
		<%= f.text_field :location %>
	</p>
	<p><%= f.submit "Add Comment" %></p>
<% end %>